# Copyright <2020> Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

name: Amazon DocumentDB JDBC Driver

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle Local Tests
      run: ./gradlew build -PrunRemoteIntegrationTests=false
    - name: Aggregate Reports
      run: |
        cp -R /common/build/test-results/test/* /build/test-results/test
        cp -R /calcite-adapter/build/test-results/test/* /build/test-results/test
        ed /common/build/reports/jacoco/test/jacocoTestReport.csv <<< $'1d\nw\nq'
        ed /calcite-adapter/build/reports/jacoco/test/jacocoTestReport.csv <<< $'1d\nw\nq'
        cat /build/reports/jacoco/test/jacocoTestReport.csv /common/build/reports/jacoco/test/jacocoTestReport.csv /calcite-adapter/build/reports/jacoco/test/jacocoTestReport.csv > /build/reports/jacoco/test/jacoco.csv
    - name: Copy Build
      run: |
        mkdir output
        mkdir output/jarfile
        mkdir output/reports
        cp build/libs/*.jar output/jarfile
        cp -R build/reports output/reports
    - name: Upload Build
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: output
    - name: Publish Summary Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.9
      if: always()
      with:
        files: build/test-results/**/*.xml
    - name: Publish Detailed Test Report
      if: always()
      uses: scacap/action-surefire-report@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        report_paths: '**/build/test-results/test/TEST-*.xml'
    - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.0.0
        with:
          jacoco-csv-file: '/build/reports/jacoco/test/jacoco.csv'
          generate-branches-badge: true

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

    - name: Commit the badge (if it changed)
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'BitQuill'
          git config --global user.email 'BitQuill@users.noreply.github.com'
          git add -A
          git commit -m "Autogenerated JaCoCo coverage badge"
          git push
        fi

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: build/reports/jacoco/
